/**
 * Parity: the TypeScript barrier wall against the Python one.
 *
 * The barrier is where a small disagreement is least forgiving. Grip is a
 * continuous function, and a 1% difference between the two sims reads as a
 * slightly different lap. A contact either happens or it does not: a wall half
 * a metre out of place is a different circuit, and a restitution that differs
 * in the third decimal is a different accident.
 *
 * So this pins both halves. The *geometry* — where the wall stands — is checked
 * against the standoff exported with the track, since `Barriers` and the
 * renderer both read that same array. The *response* is checked against traces
 * of a car staged beside a wall and driven into it, generated by
 * ``python export_web_assets.py --fixtures``.
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { Barriers, WALL_FRICTION, WALL_RESTITUTION } from './barriers'
import { Car } from './car'
import { handlingPreset } from './carParams'
import { obbCorners, PENETRATION_SLOP } from './collision'
import {
  clearOfCircuit, outsideWall, pointAt, safeOutside, safeOutsideBox,
} from './placement'
import { OFF_TRACK_GRIP, OFF_TRACK_MARGIN, OFF_TRACK_ROLLING, DT, SUBSTEPS } from './sim'
import { Track, type TrackData } from './track'

interface BarrierCase {
  name: string
  track: string
  steer: number
  throttle: number
  steps: number
  /** Ticks on which the car was penetrating a wall, impulse or not. */
  touchTicks: number
  start: Record<string, number>
  states: number[][]
  impulses: number[]
}

interface BarrierFixture {
  dt: number
  substeps: number
  sampleEvery: number
  stateKeys: string[]
  preset: string
  wall: {
    restitution: number
    friction: number
    iterations: number
    penetrationSlop: number
  }
  cases: BarrierCase[]
}

const fx = JSON.parse(
  readFileSync(fileURLToPath(new URL('./__fixtures__/barriers.json', import.meta.url)), 'utf-8'),
) as BarrierFixture

/** Python's snake_case state keys to the TypeScript field names. */
const STATE_FIELD: Record<string, string> = {
  x: 'x', y: 'y', yaw: 'yaw', vx: 'vx', vy: 'vy', r: 'r',
  steer: 'steer', wheel_v_r: 'wheelVr', slip_f: 'slipF', slip_r: 'slipR',
  gear: 'gear', shift_timer: 'shiftTimer', engine_rpm: 'engineRpm',
}

const trackCache = new Map<string, Track>()
function loadBaked(id: string): Track {
  let t = trackCache.get(id)
  if (!t) {
    const path = fileURLToPath(new URL(`../../public/tracks/${id}.json`, import.meta.url))
    t = new Track(JSON.parse(readFileSync(path, 'utf-8')) as TrackData)
    trackCache.set(id, t)
  }
  return t
}

describe('wall constants match Python', () => {
  it('restitution, friction and slop are the same numbers', () => {
    expect(WALL_RESTITUTION).toBe(fx.wall.restitution)
    expect(WALL_FRICTION).toBe(fx.wall.friction)
    expect(PENETRATION_SLOP).toBe(fx.wall.penetrationSlop)
  })

  it('the fixture was generated at this tick rate', () => {
    expect(fx.dt).toBeCloseTo(DT, 15)
    expect(fx.substeps).toBe(SUBSTEPS)
  })
})

describe('the wall stands where the track says it does', () => {
  for (const id of ['balanced_8', 'power_8']) {
    it(`${id}: the limit is half-width plus the baked gap`, () => {
      const t = loadBaked(id)
      // At frac 0 the interpolation must land exactly on the vertex values —
      // that is the join between the collision surface and the drawn one.
      for (const seg of [0, 17, 200, t.n - 1]) {
        expect(t.barrierLimit(seg, 0, false)).toBeCloseTo(
          t.halfRing[seg]! + t.barrierGapLeft[seg]!, 12,
        )
        expect(t.barrierLimit(seg, 0, true)).toBeCloseTo(
          t.halfRing[seg]! + t.barrierGapRight[seg]!, 12,
        )
      }
    })

    it(`${id}: the wall is never on the circuit`, () => {
      // `_clamp_off_track` on the Python side exists to guarantee this. If a
      // bake ever violated it, the wall would sit across the racing line and
      // the lap would be undrivable — worth asserting rather than assuming.
      const t = loadBaked(id)
      for (let i = 0; i < t.n; i++) {
        expect(t.barrierGapLeft[i]!).toBeGreaterThan(0)
        expect(t.barrierGapRight[i]!).toBeGreaterThan(0)
      }
    })

    it(`${id}: the broad-phase gate never misses a real contact`, () => {
      // `mayTouch` is an optimisation, so the only thing that matters is that
      // it never returns false while `contact` would have returned something.
      // Swept round the whole lap at offsets that straddle the wall.
      const t = loadBaked(id)
      const p = handlingPreset('f1')
      const car = new Car(p)
      for (let seg = 0; seg < t.n; seg += 7) {
        const pose = t.poseAt(t.segLenAt(seg) * seg)
        const limit = t.barrierLimit(seg, 0, false)
        for (const frac of [0.9, 0.98, 1.0, 1.02, 1.1]) {
          const off = limit * frac
          car.s.x = pose.x - Math.sin(pose.yaw) * off
          car.s.y = pose.y + Math.cos(pose.yaw) * off
          car.s.yaw = pose.yaw
          const barriers = new Barriers(t)
          const proj = t.project(car.s.x, car.s.y)
          if (barriers.contact(car.s, p) !== null) {
            expect(barriers.mayTouch(proj.lateral, p)).toBe(true)
          }
        }
      }
    })
  }
})

describe('scenery is never placed on the circuit', () => {
  // The invariant `scenery.ts` broke, and the reason `core/placement.ts`
  // exists. Offsetting a closed curve sideways is only safe for small offsets:
  // on a circuit that winds back past itself a large one walks the point across
  // the infield and onto a different part of the lap. Placing against the lap's
  // MAXIMUM runoff put grandstands on the road through Croft Bay's second
  // sector; placing against the local gap fixes most of it, but a 24 m car park
  // at Croft Bay's start line still lands on the road, which is why the offset
  // alone is not the answer and `safeOutside` pulls in until it is clear.
  const BEYOND = [5.6, 7, 13, 18, 22, 24]

  for (const id of ['balanced_8', 'power_8']) {
    it(`${id}: safeOutside always lands clear of the wall`, () => {
      const t = loadBaked(id)
      for (let i = 0; i < t.n; i++) {
        const arc = (i / t.n) * t.length
        for (const side of [1, -1]) {
          for (const beyond of BEYOND) {
            const off = safeOutside(t, arc, side, beyond)
            // Null is a legitimate answer — where the lap doubles back, every
            // point outside one wall is inside the other, and there is nowhere
            // to stand. What must never happen is a NUMBER that is on the road.
            if (off === null) continue
            const p = pointAt(t, arc, off)
            expect(
              clearOfCircuit(t, p.x, p.y),
              `${id} arc ${arc.toFixed(0)} side ${side} +${beyond}: inside the wall`,
            ).toBe(true)
          }
        }
      }
    })

    it(`${id}: safeOutsideBox clears a long building's whole footprint`, () => {
      // The bug the anchor-only guard could not catch. A 58 m pit block is
      // fine at its anchor and in the middle of the road thirty metres later,
      // where the circuit curved out from under it. Corners, not centres.
      const t = loadBaked(id)
      for (const [len, wide] of [[46, 18], [20, 9], [8, 8]] as const) {
        for (let i = 0; i < t.n; i += 3) {
          const arc = (i / t.n) * t.length
          for (const side of [1, -1]) {
            const off = safeOutsideBox(t, arc, side, 18, len, wide)
            if (off === null) continue
            const c = pointAt(t, arc, off)
            const pose = t.poseAt(arc)
            const fx = Math.cos(pose.yaw)
            const fy = Math.sin(pose.yaw)
            for (const u of [-0.5, 0, 0.5]) {
              for (const v of [-0.5, 0, 0.5]) {
                const x = c.x + fx * u * len - fy * v * wide
                const y = c.y + fy * u * len + fx * v * wide
                expect(
                  clearOfCircuit(t, x, y),
                  `${id} ${len}x${wide} arc ${arc.toFixed(0)} side ${side} corner ${u},${v}`,
                ).toBe(true)
              }
            }
          }
        }
      }
    })

    it(`${id}: safeOutside only gives up room when it has to`, () => {
      // A guard that solved the problem by refusing to place anything, or by
      // jamming it all against the wall, would pass the test above and ruin the
      // circuit. Most of the lap has room and should still be given it.
      const t = loadBaked(id)
      let full = 0
      let total = 0
      for (let i = 0; i < t.n; i++) {
        const arc = (i / t.n) * t.length
        for (const side of [1, -1]) {
          total++
          if (safeOutside(t, arc, side, 18) === outsideWall(t, arc, side, 18)) full++
        }
      }
      expect(full / total, `${id}: fraction of the lap with full room`).toBeGreaterThan(0.8)
    })
  }
})

describe('the hitbox is the drawn rectangle', () => {
  it('corners are front-left, front-right, rear-right, rear-left', () => {
    // Axis-aligned: yaw 0 means +x is forward and +y is left, so the first
    // corner is front-left. Matches Python's `_UNIT_CORNERS` ordering, which is
    // what makes the contact centroid mean the same thing on both sides.
    const c = obbCorners(0, 0, 0, 4, 2)
    expect(Array.from(c)).toEqual([2, 1, 2, -1, -2, -1, -2, 1])
  })

  it('rotates about the centre', () => {
    const c = obbCorners(10, -5, Math.PI / 2, 4, 2)
    expect(c[0]!).toBeCloseTo(10 - 1, 12)
    expect(c[1]!).toBeCloseTo(-5 + 2, 12)
  })
})

describe('collision traces match Python', () => {
  // The same per-field tolerances `car.test.ts` uses. A contact is a much
  // stiffer event than free driving — one tick can turn 60 m/s into 40 — so if
  // anything in the impulse maths differed at all, it would show up here at a
  // scale these tolerances cannot hide.
  const tol: Record<string, number> = {
    x: 1e-9, y: 1e-9, yaw: 1e-11,
    vx: 1e-9, vy: 1e-9, r: 1e-11,
    steer: 1e-12, wheel_v_r: 1e-9,
    slip_f: 1e-11, slip_r: 1e-11,
    gear: 0, shift_timer: 1e-12, engine_rpm: 1e-7,
  }

  for (const c of fx.cases) {
    it(`${c.track} / ${c.name}`, () => {
      const track = loadBaked(c.track)
      const p = handlingPreset(fx.preset as 'f1')
      const barriers = new Barriers(track)
      const car = new Car(p)
      const state = car.s as unknown as Record<string, number>
      for (const [key, value] of Object.entries(c.start)) {
        state[STATE_FIELD[key]!] = value
      }

      let row = 0
      const check = (peak: number): void => {
        const expected = c.states[row]!
        for (let f = 0; f < fx.stateKeys.length; f++) {
          const key = fx.stateKeys[f]!
          const got = state[STATE_FIELD[key]!]!
          const want = expected[f]!
          expect(
            Math.abs(got - want),
            `${c.name} row ${row} field ${key}: got ${got}, want ${want}`,
          ).toBeLessThanOrEqual(tol[key]!)
        }
        expect(
          Math.abs(peak - c.impulses[row]!),
          `${c.name} row ${row} impulse: got ${peak}, want ${c.impulses[row]}`,
        ).toBeLessThanOrEqual(1e-6)
        row++
      }

      check(0)
      let peak = 0
      let touched = 0
      for (let i = 0; i < c.steps; i++) {
        const s = car.s
        const proj = track.project(s.x, s.y)
        const onGrass = Math.abs(proj.lateral) > proj.half + OFF_TRACK_MARGIN
        car.step(
          c.steer, c.throttle, DT, SUBSTEPS,
          onGrass ? OFF_TRACK_GRIP : 1.0,
          onGrass ? OFF_TRACK_ROLLING : 1.0,
        )
        const after = track.project(s.x, s.y)
        if (barriers.mayTouch(after.lateral, p)) {
          if (barriers.contact(s, p) !== null) touched++
          peak = Math.max(peak, barriers.resolve(s, p))
        }
        if ((i + 1) % fx.sampleEvery === 0) {
          check(peak)
          peak = 0
        }
      }
      // Counted separately from the impulse and asserted separately, because
      // they are different things: `already_inside` is a resolved contact that
      // returns zero, since the car has no velocity into the wall. Agreeing on
      // the impulse alone would let the two sides disagree about whether a
      // touch happened at all.
      expect(touched, `${c.name}: ticks in contact`).toBe(c.touchTicks)
    })
  }

  it('the clear case really never touches a wall', () => {
    // Guards the guard: if staging drifted and this case started brushing a
    // barrier, it would still pass the trace comparison above while silently
    // no longer testing that an untouched lap is unaffected by the walls.
    const clear = fx.cases.find((c) => c.name === 'clear_of_walls')!
    expect(clear.touchTicks).toBe(0)
  })

  it('a case that is inside the wall with no closing speed still resolves', () => {
    // The path that made `sim.ts` re-project unconditionally rather than only
    // when the impulse was non-zero. If this ever stops being true the fixture
    // has drifted and that branch is no longer covered by anything.
    const pushed = fx.cases.find((c) => c.name === 'already_inside')!
    expect(pushed.touchTicks).toBeGreaterThan(0)
    expect(Math.max(...pushed.impulses)).toBe(0)
  })
})
