/**
 * Parity: the TypeScript car against the Python car.
 *
 * The fixtures are generated by ``python export_web_assets.py --fixtures`` and
 * hold, for every handling preset, the state trace produced by driving through a
 * set of scripted control schedules chosen to exercise each branch of the
 * integrator.
 *
 * Exact bit-parity is not achievable and is not claimed: ``sin``, ``cos``,
 * ``atan`` and friends are not precision-specified in either language, so the
 * two diverge in the last bits and the difference compounds over 3600 integration
 * sub-steps. What is asserted is that the divergence stays far below anything a
 * driver or an agent could perceive.
 *
 * The parameter check runs first and is exact. A mistyped constant is the
 * likeliest port bug by a wide margin, and it would otherwise show up here as a
 * confusing trajectory failure a long way from its cause.
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { Car } from './car'
import { applyEasyAids, handlingPreset, type CarParams, type PresetName } from './carParams'

interface Fixtures {
  dt: number
  substeps: number
  steps: number
  sampleEvery: number
  stateKeys: string[]
  constants: Record<string, unknown>
  presets: Record<string, Record<string, unknown>>
  cases: FixtureCase[]
  traces: { preset: string; case: string; states: number[][] }[]
}

interface FixtureCase {
  name: string
  note: string
  schedule: number[][]
  initial?: Record<string, number>
  grip_mult?: number
  rolling_mult?: number
}

const fixturePath = fileURLToPath(new URL('./__fixtures__/physics.json', import.meta.url))
const fx = JSON.parse(readFileSync(fixturePath, 'utf-8')) as Fixtures

const snakeToCamel = (s: string): string => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())

/**
 * Python state field -> TypeScript state field.
 *
 * Spelled out rather than derived, because ``wheel_v_r`` camelises to
 * ``wheelVR``, which is not what the field is called. An explicit table is also
 * the thing to update when a state field is added, and it fails loudly if one is
 * added on only one side.
 */
const STATE_FIELD: Record<string, string> = {
  x: 'x',
  y: 'y',
  yaw: 'yaw',
  vx: 'vx',
  vy: 'vy',
  r: 'r',
  steer: 'steer',
  wheel_v_r: 'wheelVr',
  slip_f: 'slipF',
  slip_r: 'slipR',
  gear: 'gear',
  shift_timer: 'shiftTimer',
  engine_rpm: 'engineRpm',
}

/** Build the TS params for a fixture preset key, including the `_easy` variants. */
function paramsFor(key: string): CarParams {
  if (key.endsWith('_easy')) {
    return applyEasyAids(handlingPreset(key.slice(0, -'_easy'.length) as PresetName))
  }
  return handlingPreset(key as PresetName)
}

function controlAt(schedule: number[][], i: number): [number, number] {
  for (const entry of schedule) {
    if (i < entry[0]!) return [entry[1]!, entry[2]!]
  }
  const last = schedule[schedule.length - 1]!
  return [last[1]!, last[2]!]
}

describe('module constants match Python', () => {
  it('carries the same Pacejka coefficients and torque curve', () => {
    const c = fx.constants
    expect(c['G']).toBe(9.81)
    expect(c['PAC_B']).toBe(10.5)
    expect(c['PAC_C']).toBe(1.35)
    expect(c['PAC_E']).toBe(-1.0)
    expect(c['TQ_RPM']).toEqual([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 8200])
    expect(c['TQ_NM']).toEqual([360, 520, 650, 710, 715, 690, 630, 540, 500])
  })
})

describe('handling presets match Python exactly', () => {
  for (const [key, pyParams] of Object.entries(fx.presets)) {
    it(`${key} has identical parameters`, () => {
      const ts = paramsFor(key) as unknown as Record<string, unknown>

      // Key sets must match, so a parameter added in Python and forgotten here
      // fails loudly instead of silently keeping a stale default.
      const pyKeys = Object.keys(pyParams).map(snakeToCamel).sort()
      expect(Object.keys(ts).sort()).toEqual(pyKeys)

      for (const [pyKey, pyValue] of Object.entries(pyParams)) {
        const tsValue = ts[snakeToCamel(pyKey)]
        if (Array.isArray(pyValue)) {
          expect(tsValue, pyKey).toEqual(pyValue)
        } else {
          // Exact: these are literals on both sides, not computed results.
          expect(tsValue, pyKey).toBe(pyValue)
        }
      }
    })
  }
})

describe('state traces match Python', () => {
  const caseByName = new Map(fx.cases.map((c) => [c.name, c]))

  // Per-field absolute tolerances (SI: m, rad, m/s, rad/s).
  //
  // These are set from measurement, not guessed. Across all 80 traces — 6 s of
  // driving, 3600 integration sub-steps each — the largest observed divergence
  // was:
  //
  //     x  2.8e-13    y  3.6e-13    yaw  9.5e-15    vx  1.0e-13
  //     vy 1.3e-13    r  1.8e-14    steer 4.4e-16   wheel_v_r 4.5e-13
  //     slip_f 7.5e-15   slip_r 2.2e-14   engine_rpm 3.3e-11
  //     gear and shift_timer: exact
  //
  // i.e. sub-picometre positional agreement. The tolerances below sit roughly
  // three orders of magnitude above that. The headroom is deliberate and is for
  // the *Python* side: CPython's math.sin/cos/atan come from the platform libm,
  // so regenerating the fixtures on a different OS can move the last bits.
  // V8's are a portable fdlibm and do not vary. Even so this stays about six
  // orders tighter than anything a driver or an agent could perceive.
  const tol: Record<string, number> = {
    x: 1e-9, y: 1e-9, yaw: 1e-11,
    vx: 1e-9, vy: 1e-9, r: 1e-11,
    steer: 1e-12, wheel_v_r: 1e-9,
    slip_f: 1e-11, slip_r: 1e-11,
    gear: 0, shift_timer: 1e-12, engine_rpm: 1e-7,
  }

  for (const trace of fx.traces) {
    const spec = caseByName.get(trace.case)!

    it(`${trace.preset} / ${trace.case}`, () => {
      const car = new Car(paramsFor(trace.preset))
      const state = car.s as unknown as Record<string, number>
      for (const [key, value] of Object.entries(spec.initial ?? {})) {
        state[STATE_FIELD[key]!] = value
      }

      const gripMult = spec.grip_mult ?? 1.0
      const rollingMult = spec.rolling_mult ?? 1.0

      let row = 0
      const check = (): void => {
        const expected = trace.states[row]!
        for (let f = 0; f < fx.stateKeys.length; f++) {
          const key = fx.stateKeys[f]!
          const got = (car.s as unknown as Record<string, number>)[STATE_FIELD[key]!]!
          const want = expected[f]!
          expect(
            Math.abs(got - want),
            `${trace.preset}/${trace.case} step ${row * fx.sampleEvery} field ${key}: got ${got}, want ${want}`,
          ).toBeLessThanOrEqual(tol[key]!)
        }
        row++
      }

      check() // step 0, before any input
      for (let i = 0; i < fx.steps; i++) {
        const [steer, throttle] = controlAt(spec.schedule, i)
        car.step(steer, throttle, fx.dt, fx.substeps, gripMult, rollingMult)
        if ((i + 1) % fx.sampleEvery === 0) check()
      }

      expect(row).toBe(trace.states.length)
    })
  }
})
